name: socratic
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytorch-cuda
  - pytorch
  - torchvision
  - requests
  - numpy
  - openai
  - ffmpeg
  - pip:
      - pillow
      - openai-clip
      - opencv-python-headless
      - notebook
      - profanity-filter
      - transformers
      - matplotlib
      - pycocoevalcap
      - bert-score
      - python-dotenv
      - datasets==2.10.0
      - evaluate
      - nltk
      - rouge-score
      - git+https://github.com/google-research/bleurt.git